### ISSUE TITLE
Toggling while in game?

### ISSUE THREAD

**Issue by Brandon1806** [Jimmyokok/UnlimitedElevatedRoad#2]
Is there a way to toggle the no pillars aspect of the mod off and on while in game or does it have to be done from the Thunderstore Mod Manager every time?

**Comment by Jimmyokok** [comment]
Unfortunately that's currently impossible. This mod takes effect when the game initializes all road types, by forcing most road types to be initialized as pillarless. It can't be switched in game, because once the game has been initialized, these road types would be simply pillarless until the game is restarted and everything get initialized again.

**Comment by Jimmyokok** [comment]
Updated the mod to 1.0.0 and implemented the in-game configuration function.
